---
- hosts: all
  user: vagrant
  sudo: yes


  vars:
    java_version: "7u71-2.5.3-0ubuntu0.14.04.1"

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes
  
  roles:
    - { "role": "azavea.java" }
    - { "role": "azavea.libgdal-java" }
    - { "role": "azavea.git" }
    - { "role": "geotrellis" }
